#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : fontconfig
Version  : 2.13.91
Release  : 44
URL      : file:///insilications/build/clearlinux/packages/fontconfig/fontconfig-2.13.91.tar.gz
Source0  : file:///insilications/build/clearlinux/packages/fontconfig/fontconfig-2.13.91.tar.gz
Source1  : fontconfig-trigger.service
Summary  : Font configuration and customization library
Group    : Development/Tools
License  : MIT
Requires: fontconfig-bin = %{version}-%{release}
Requires: fontconfig-data = %{version}-%{release}
Requires: fontconfig-lib = %{version}-%{release}
Requires: fontconfig-locales = %{version}-%{release}
Requires: fontconfig-services = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : buildreq-meson
BuildRequires : docbook-utils
BuildRequires : expat
BuildRequires : expat-dev
BuildRequires : expat-dev32
BuildRequires : expat-staticdev
BuildRequires : expat-staticdev32
BuildRequires : findutils
BuildRequires : fontconfig-data
BuildRequires : freetype-dev
BuildRequires : freetype-staticdev
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : gettext
BuildRequires : gettext-bin
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gperf
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : m4
BuildRequires : perl(XML::Parser)
BuildRequires : pkg-config
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(32expat)
BuildRequires : pkgconfig(32freetype2)
BuildRequires : pkgconfig(32json-c)
BuildRequires : pkgconfig(32libxml-2.0)
BuildRequires : pkgconfig(32uuid)
BuildRequires : pkgconfig(expat)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(uuid)
BuildRequires : util-linux
BuildRequires : util-linux-dev
BuildRequires : util-linux-dev32
BuildRequires : util-linux-staticdev
BuildRequires : util-linux-staticdev32
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Include-stateless-configuration.patch
Patch2: 0002-Add-spacing-config-for-Clear-Sans.patch
Patch3: 0003-Use-sane-defaults-throughout-the-system.patch
Patch4: 0004-Enforce-antialiasing-by-default.patch

%description
Fontconfig
Font configuration and customization library
Version 2.13.91 (2.14 RC1)
2019-06-10

%package bin
Summary: bin components for the fontconfig package.
Group: Binaries
Requires: fontconfig-data = %{version}-%{release}
Requires: fontconfig-services = %{version}-%{release}

%description bin
bin components for the fontconfig package.


%package data
Summary: data components for the fontconfig package.
Group: Data

%description data
data components for the fontconfig package.


%package dev
Summary: dev components for the fontconfig package.
Group: Development
Requires: fontconfig-lib = %{version}-%{release}
Requires: fontconfig-bin = %{version}-%{release}
Requires: fontconfig-data = %{version}-%{release}
Provides: fontconfig-devel = %{version}-%{release}
Requires: fontconfig = %{version}-%{release}

%description dev
dev components for the fontconfig package.


%package dev32
Summary: dev32 components for the fontconfig package.
Group: Default
Requires: fontconfig-lib32 = %{version}-%{release}
Requires: fontconfig-bin = %{version}-%{release}
Requires: fontconfig-data = %{version}-%{release}
Requires: fontconfig-dev = %{version}-%{release}

%description dev32
dev32 components for the fontconfig package.


%package lib
Summary: lib components for the fontconfig package.
Group: Libraries
Requires: fontconfig-data = %{version}-%{release}

%description lib
lib components for the fontconfig package.


%package lib32
Summary: lib32 components for the fontconfig package.
Group: Default
Requires: fontconfig-data = %{version}-%{release}

%description lib32
lib32 components for the fontconfig package.


%package locales
Summary: locales components for the fontconfig package.
Group: Default

%description locales
locales components for the fontconfig package.


%package services
Summary: services components for the fontconfig package.
Group: Systemd services

%description services
services components for the fontconfig package.


%package staticdev
Summary: staticdev components for the fontconfig package.
Group: Default
Requires: fontconfig-dev = %{version}-%{release}

%description staticdev
staticdev components for the fontconfig package.


%package staticdev32
Summary: staticdev32 components for the fontconfig package.
Group: Default
Requires: fontconfig-dev = %{version}-%{release}

%description staticdev32
staticdev32 components for the fontconfig package.


%prep
%setup -q -n fontconfig
cd %{_builddir}/fontconfig
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
pushd ..
cp -a fontconfig build32
popd

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1599679515
export GCC_IGNORE_WERROR=1
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -fPIC $PGO_GEN"
export FCFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -fPIC $PGO_GEN"
export FFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -fPIC $PGO_GEN"
export CXXFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC $PGO_GEN"
export LDFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -flimit-function-alignment -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -ffat-lto-objects -fPIC $PGO_GEN"
## pgo use
## -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden -flto-partition=none
## gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC $PGO_USE"
export FCFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC $PGO_USE"
export FFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC $PGO_USE"
export CXXFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC $PGO_USE"
export LDFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC $PGO_USE"
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%define _lto_cflags 1
#%define _lto_cflags %{nil}
#
# export PATH="/usr/lib64/ccache/bin:$PATH"
# export CCACHE_NOHASHDIR=1
# export CCACHE_DIRECT=1
# export CCACHE_SLOPPINESS=pch_defines,locale,time_macros
# export CCACHE_DISABLE=1
## altflags_pgo end
##
%define _lto_cflags 1
##
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
%autogen --enable-static --enable-shared --sysconfdir=/usr/share/defaults --disable-docs
make  %{?_smp_mflags}  VERBOSE=1 V=1

make VERBOSE=1 V=1 %{?_smp_mflags} check || :
make clean
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
%autogen  --enable-static --enable-shared --sysconfdir=/usr/share/defaults --disable-docs
make  %{?_smp_mflags}  VERBOSE=1 V=1

pushd ../build32/
export CFLAGS="-g -O2 -fuse-linker-plugin -pipe"
export CXXFLAGS="-g -O2 -fuse-linker-plugin -fvisibility-inlines-hidden -pipe"
export LDFLAGS="-g -O2 -fuse-linker-plugin -pipe"
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
unset LD_LIBRARY_PATH
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%autogen  --enable-static --enable-shared --sysconfdir=/usr/share/defaults --disable-docs  --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}  VERBOSE=1 V=1
popd

%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
make %{?_smp_mflags} check || :
cd ../build32;
make %{?_smp_mflags} check || : || :

%install
export SOURCE_DATE_EPOCH=1599679515
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
%find_lang fontconfig-conf
%find_lang fontconfig
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/fontconfig-trigger.service
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants/
ln -s ../fontconfig-trigger.service  %{buildroot}/usr/lib/systemd/system/update-triggers.target.wants/fontconfig-trigger.service
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fc-cache
/usr/bin/fc-cat
/usr/bin/fc-conflist
/usr/bin/fc-list
/usr/bin/fc-match
/usr/bin/fc-pattern
/usr/bin/fc-query
/usr/bin/fc-scan
/usr/bin/fc-validate

%files data
%defattr(-,root,root,-)
/usr/share/defaults/fonts/conf.d/10-hinting-slight.conf
/usr/share/defaults/fonts/conf.d/10-scale-bitmap-fonts.conf
/usr/share/defaults/fonts/conf.d/20-unhint-clear-sans.conf
/usr/share/defaults/fonts/conf.d/20-unhint-small-vera.conf
/usr/share/defaults/fonts/conf.d/30-metric-aliases.conf
/usr/share/defaults/fonts/conf.d/40-nonlatin.conf
/usr/share/defaults/fonts/conf.d/45-generic.conf
/usr/share/defaults/fonts/conf.d/45-latin.conf
/usr/share/defaults/fonts/conf.d/49-sansserif.conf
/usr/share/defaults/fonts/conf.d/50-user.conf
/usr/share/defaults/fonts/conf.d/51-local.conf
/usr/share/defaults/fonts/conf.d/60-generic.conf
/usr/share/defaults/fonts/conf.d/60-latin.conf
/usr/share/defaults/fonts/conf.d/65-fonts-persian.conf
/usr/share/defaults/fonts/conf.d/65-nonlatin.conf
/usr/share/defaults/fonts/conf.d/69-unifont.conf
/usr/share/defaults/fonts/conf.d/80-delicious.conf
/usr/share/defaults/fonts/conf.d/90-synthetic.conf
/usr/share/defaults/fonts/conf.d/README
/usr/share/defaults/fonts/fonts.conf
/usr/share/defaults/fonts/fonts.conf.bak
/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf
/usr/share/fontconfig/conf.avail/09-autohint-if-no-hinting.conf
/usr/share/fontconfig/conf.avail/10-antialiasing.conf
/usr/share/fontconfig/conf.avail/10-autohint.conf
/usr/share/fontconfig/conf.avail/10-hinting-full.conf
/usr/share/fontconfig/conf.avail/10-hinting-medium.conf
/usr/share/fontconfig/conf.avail/10-hinting-none.conf
/usr/share/fontconfig/conf.avail/10-hinting-slight.conf
/usr/share/fontconfig/conf.avail/10-no-sub-pixel.conf
/usr/share/fontconfig/conf.avail/10-scale-bitmap-fonts.conf
/usr/share/fontconfig/conf.avail/10-sub-pixel-bgr.conf
/usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf
/usr/share/fontconfig/conf.avail/10-sub-pixel-vbgr.conf
/usr/share/fontconfig/conf.avail/10-sub-pixel-vrgb.conf
/usr/share/fontconfig/conf.avail/10-unhinted.conf
/usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf
/usr/share/fontconfig/conf.avail/11-lcdfilter-legacy.conf
/usr/share/fontconfig/conf.avail/11-lcdfilter-light.conf
/usr/share/fontconfig/conf.avail/20-unhint-clear-sans.conf
/usr/share/fontconfig/conf.avail/20-unhint-small-vera.conf
/usr/share/fontconfig/conf.avail/25-unhint-nonlatin.conf
/usr/share/fontconfig/conf.avail/30-metric-aliases.conf
/usr/share/fontconfig/conf.avail/35-lang-normalize.conf
/usr/share/fontconfig/conf.avail/40-nonlatin.conf
/usr/share/fontconfig/conf.avail/45-generic.conf
/usr/share/fontconfig/conf.avail/45-latin.conf
/usr/share/fontconfig/conf.avail/49-sansserif.conf
/usr/share/fontconfig/conf.avail/50-user.conf
/usr/share/fontconfig/conf.avail/51-local.conf
/usr/share/fontconfig/conf.avail/60-generic.conf
/usr/share/fontconfig/conf.avail/60-latin.conf
/usr/share/fontconfig/conf.avail/65-fonts-persian.conf
/usr/share/fontconfig/conf.avail/65-khmer.conf
/usr/share/fontconfig/conf.avail/65-nonlatin.conf
/usr/share/fontconfig/conf.avail/69-unifont.conf
/usr/share/fontconfig/conf.avail/70-no-bitmaps.conf
/usr/share/fontconfig/conf.avail/70-yes-bitmaps.conf
/usr/share/fontconfig/conf.avail/80-delicious.conf
/usr/share/fontconfig/conf.avail/90-synthetic.conf
/usr/share/gettext/its/fontconfig.its
/usr/share/gettext/its/fontconfig.loc
/usr/share/xml/fontconfig/fonts.dtd

%files dev
%defattr(-,root,root,-)
/usr/include/fontconfig/fcfreetype.h
/usr/include/fontconfig/fcprivate.h
/usr/include/fontconfig/fontconfig.h
/usr/lib64/libfontconfig.so
/usr/lib64/pkgconfig/fontconfig.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libfontconfig.so
/usr/lib32/pkgconfig/32fontconfig.pc
/usr/lib32/pkgconfig/fontconfig.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfontconfig.so.1
/usr/lib64/libfontconfig.so.1.12.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libfontconfig.so.1
/usr/lib32/libfontconfig.so.1.12.0

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/fontconfig-trigger.service
/usr/lib/systemd/system/update-triggers.target.wants/fontconfig-trigger.service

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libfontconfig.a

%files staticdev32
%defattr(-,root,root,-)
/usr/lib32/libfontconfig.a

%files locales -f fontconfig-conf.lang -f fontconfig.lang
%defattr(-,root,root,-)

